name: Test, Build, Publish and Deploy Backend API Application

on:
  push:
    branches:
      - main

env:
  IMAGE: alvynabranches/dummy

jobs:
  build-publish:
    name: Build Publish to DockerHub
    runs-on: ubuntu-latest
    environment: Prod

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      # Working
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      # Working
      - name: Build Docker Image
        run: |
          make build

      # Working
      - name: Push Docker Image
        run: |
          make push
